import '../models/models.dart';
import '../core/enums/enums.dart';

/// Mock data service providing realistic Moroccan demo data
/// Replace with real API calls when backend is ready
class MockDataService {
  static final MockDataService _instance = MockDataService._internal();
  factory MockDataService() => _instance;
  MockDataService._internal();

  // Current user (demo)
  UserModel get currentUser => UserModel(
        id: 'user_001',
        fullName: 'Aziz Bennani',
        phone: '+212 6 12 34 56 78',
        email: 'aziz@example.com',
        city: 'Casablanca',
        role: UserRole.customer,
        createdAt: DateTime(2024, 1, 15),
        latitude: 33.5731,
        longitude: -7.5898,
        favoriteProIds: ['pro_001', 'pro_003'],
      );

  // Demo professionals
  List<ProfessionalModel> get professionals => [
        ProfessionalModel(
          id: 'pro_001',
          userId: 'user_pro_001',
          fullName: 'Yassine El Amrani',
          phone: '+212 6 55 12 34 56',
          city: 'Casablanca',
          bio:
              'Plombier professionnel avec plus de 8 ans d\'expérience. Intervention rapide dans tout Casablanca et Mohammedia. Spécialiste en réparation de fuites, installation sanitaire et débouchage.',
          services: [ServiceCategory.plumber],
          serviceAreas: ['Casablanca', 'Mohammedia', 'Ain Sebaa', 'Hay Hassani'],
          rating: 4.8,
          reviewCount: 124,
          completedJobs: 187,
          yearsExperience: 8,
          startingPrice: 100,
          workingHours: {
            'monday': '08:00 - 18:00',
            'tuesday': '08:00 - 18:00',
            'wednesday': '08:00 - 18:00',
            'thursday': '08:00 - 18:00',
            'friday': '08:00 - 12:00, 14:00 - 18:00',
            'saturday': '09:00 - 14:00',
            'sunday': 'Fermé',
          },
          verificationStatus: VerificationStatus.verified,
          availabilityStatus: AvailabilityStatus.available,
          latitude: 33.5850,
          longitude: -7.6100,
          createdAt: DateTime(2023, 6, 10),
        ),
        ProfessionalModel(
          id: 'pro_002',
          userId: 'user_pro_002',
          fullName: 'Fatima Zahra Alaoui',
          phone: '+212 7 00 98 76 54',
          city: 'Casablanca',
          bio:
              'Spécialiste en nettoyage résidentiel et commercial. Équipe professionnelle et produits de qualité. Nous assurons un nettoyage complet de votre maison.',
          services: [ServiceCategory.cleaning],
          serviceAreas: ['Casablanca', 'Ain Diab', 'Maarif', 'Gauthier'],
          rating: 4.9,
          reviewCount: 203,
          completedJobs: 312,
          yearsExperience: 5,
          startingPrice: 150,
          workingHours: {
            'monday': '07:00 - 19:00',
            'tuesday': '07:00 - 19:00',
            'wednesday': '07:00 - 19:00',
            'thursday': '07:00 - 19:00',
            'friday': '07:00 - 12:00',
            'saturday': '08:00 - 16:00',
            'sunday': 'Fermé',
          },
          verificationStatus: VerificationStatus.verified,
          availabilityStatus: AvailabilityStatus.available,
          latitude: 33.5700,
          longitude: -7.6300,
          createdAt: DateTime(2023, 3, 20),
        ),
        ProfessionalModel(
          id: 'pro_003',
          userId: 'user_pro_003',
          fullName: 'Mohamed Tazi',
          phone: '+212 6 61 23 45 67',
          city: 'Casablanca',
          bio:
              'Électricien certifié, installation et dépannage électrique. Tableaux, prises, éclairage, domotique. Devis gratuit et intervention rapide.',
          services: [ServiceCategory.electrician],
          serviceAreas: ['Casablanca', 'Mohammedia', 'Berrechid'],
          rating: 4.7,
          reviewCount: 89,
          completedJobs: 134,
          yearsExperience: 12,
          startingPrice: 120,
          workingHours: {
            'monday': '08:00 - 18:00',
            'tuesday': '08:00 - 18:00',
            'wednesday': '08:00 - 18:00',
            'thursday': '08:00 - 18:00',
            'friday': '08:00 - 12:00, 14:00 - 18:00',
            'saturday': '09:00 - 13:00',
            'sunday': 'Fermé',
          },
          verificationStatus: VerificationStatus.verified,
          availabilityStatus: AvailabilityStatus.available,
          latitude: 33.5900,
          longitude: -7.5800,
          createdAt: DateTime(2022, 11, 5),
        ),
        ProfessionalModel(
          id: 'pro_004',
          userId: 'user_pro_004',
          fullName: 'Khalid Benhaddou',
          phone: '+212 6 78 90 12 34',
          city: 'Rabat',
          bio:
              'Peintre professionnel. Peinture intérieure et extérieure, ravalement de façade, enduit décoratif. Travail soigné et finitions parfaites.',
          services: [ServiceCategory.painting],
          serviceAreas: ['Rabat', 'Salé', 'Témara'],
          rating: 4.6,
          reviewCount: 67,
          completedJobs: 95,
          yearsExperience: 10,
          startingPrice: 50,
          workingHours: {
            'monday': '07:00 - 17:00',
            'tuesday': '07:00 - 17:00',
            'wednesday': '07:00 - 17:00',
            'thursday': '07:00 - 17:00',
            'friday': '07:00 - 12:00',
            'saturday': '08:00 - 14:00',
            'sunday': 'Fermé',
          },
          verificationStatus: VerificationStatus.verified,
          availabilityStatus: AvailabilityStatus.busy,
          latitude: 34.0209,
          longitude: -6.8416,
          createdAt: DateTime(2023, 1, 15),
        ),
        ProfessionalModel(
          id: 'pro_005',
          userId: 'user_pro_005',
          fullName: 'Rachid Moussaoui',
          phone: '+212 6 34 56 78 90',
          city: 'Marrakech',
          bio:
              'Technicien en réparation d\'appareils électroménagers. Machine à laver, réfrigérateur, climatiseur, four, lave-vaisselle. Intervention à domicile.',
          services: [ServiceCategory.applianceRepair, ServiceCategory.airConditioning],
          serviceAreas: ['Marrakech', 'Guéliz', 'Médina'],
          rating: 4.5,
          reviewCount: 156,
          completedJobs: 234,
          yearsExperience: 15,
          startingPrice: 100,
          workingHours: {
            'monday': '08:00 - 18:00',
            'tuesday': '08:00 - 18:00',
            'wednesday': '08:00 - 18:00',
            'thursday': '08:00 - 18:00',
            'friday': '08:00 - 12:00, 14:00 - 18:00',
            'saturday': '09:00 - 14:00',
            'sunday': 'Fermé',
          },
          verificationStatus: VerificationStatus.verified,
          availabilityStatus: AvailabilityStatus.available,
          latitude: 31.6295,
          longitude: -7.9811,
          createdAt: DateTime(2022, 8, 20),
        ),
        ProfessionalModel(
          id: 'pro_006',
          userId: 'user_pro_006',
          fullName: 'Hassan Idrissi',
          phone: '+212 6 45 67 89 01',
          city: 'Casablanca',
          bio:
              'Menuisier qualifié. Fabrication sur mesure, placards, cuisines, portes, fenêtres en bois et aluminium. Travail artisanal de qualité.',
          services: [ServiceCategory.carpenter],
          serviceAreas: ['Casablanca', 'Bouskoura', 'Dar Bouazza'],
          rating: 4.4,
          reviewCount: 45,
          completedJobs: 78,
          yearsExperience: 20,
          startingPrice: 200,
          workingHours: {
            'monday': '08:00 - 17:00',
            'tuesday': '08:00 - 17:00',
            'wednesday': '08:00 - 17:00',
            'thursday': '08:00 - 17:00',
            'friday': '08:00 - 12:00',
            'saturday': '09:00 - 13:00',
            'sunday': 'Fermé',
          },
          verificationStatus: VerificationStatus.verified,
          availabilityStatus: AvailabilityStatus.available,
          latitude: 33.5650,
          longitude: -7.6200,
          createdAt: DateTime(2023, 4, 10),
        ),
        ProfessionalModel(
          id: 'pro_007',
          userId: 'user_pro_007',
          fullName: 'Abdellatif Chraibi',
          phone: '+212 7 12 34 56 78',
          city: 'Tangier',
          bio:
              'Mécanicien automobile professionnel. Diagnostic, réparation, entretien. Toutes marques. Intervention à domicile possible.',
          services: [ServiceCategory.mechanic],
          serviceAreas: ['Tangier', 'Tétouan'],
          rating: 4.3,
          reviewCount: 92,
          completedJobs: 156,
          yearsExperience: 14,
          startingPrice: 150,
          workingHours: {
            'monday': '08:00 - 18:00',
            'tuesday': '08:00 - 18:00',
            'wednesday': '08:00 - 18:00',
            'thursday': '08:00 - 18:00',
            'friday': '08:00 - 12:00, 14:00 - 18:00',
            'saturday': '09:00 - 15:00',
            'sunday': 'Fermé',
          },
          verificationStatus: VerificationStatus.pending,
          availabilityStatus: AvailabilityStatus.available,
          latitude: 35.7595,
          longitude: -5.8340,
          createdAt: DateTime(2023, 7, 1),
        ),
        ProfessionalModel(
          id: 'pro_008',
          userId: 'user_pro_008',
          fullName: 'Samir Ouahbi',
          phone: '+212 6 89 01 23 45',
          city: 'Fès',
          bio:
              'Service de déménagement professionnel. Transport de meubles, emballage, montage et démontage. Camion équipé et équipe qualifiée.',
          services: [ServiceCategory.moving],
          serviceAreas: ['Fès', 'Meknès', 'Ifrane'],
          rating: 4.6,
          reviewCount: 78,
          completedJobs: 112,
          yearsExperience: 7,
          startingPrice: 500,
          workingHours: {
            'monday': '06:00 - 20:00',
            'tuesday': '06:00 - 20:00',
            'wednesday': '06:00 - 20:00',
            'thursday': '06:00 - 20:00',
            'friday': '06:00 - 12:00',
            'saturday': '07:00 - 18:00',
            'sunday': 'Sur rendez-vous',
          },
          verificationStatus: VerificationStatus.verified,
          availabilityStatus: AvailabilityStatus.available,
          latitude: 34.0331,
          longitude: -5.0003,
          createdAt: DateTime(2023, 2, 15),
        ),
      ];

  // Demo service requests
  List<ServiceRequest> get serviceRequests => [
        ServiceRequest(
          id: 'req_001',
          customerId: 'user_001',
          professionalId: 'pro_001',
          customerName: 'Aziz Bennani',
          professionalName: 'Yassine El Amrani',
          category: ServiceCategory.plumber,
          description:
              'Fuite d\'eau dans la cuisine, sous l\'évier. L\'eau coule en continu et j\'ai dû couper l\'arrivée d\'eau.',
          latitude: 33.5731,
          longitude: -7.5898,
          address: '45 Rue Mohamed V, Maarif',
          city: 'Casablanca',
          preferredDate: DateTime.now().add(const Duration(days: 1)),
          preferredTime: '10:00',
          budget: 150,
          estimatedPrice: 120,
          status: RequestStatus.accepted,
          paymentMethod: PaymentMethod.cash,
          createdAt: DateTime.now().subtract(const Duration(hours: 3)),
          acceptedAt: DateTime.now().subtract(const Duration(hours: 1)),
        ),
        ServiceRequest(
          id: 'req_002',
          customerId: 'user_001',
          professionalId: 'pro_002',
          customerName: 'Aziz Bennani',
          professionalName: 'Fatima Zahra Alaoui',
          category: ServiceCategory.cleaning,
          description:
              'Nettoyage complet d\'un appartement de 3 chambres avant emménagement. Nettoyage profond de la cuisine et des salles de bain.',
          latitude: 33.5731,
          longitude: -7.5898,
          address: '12 Boulevard Zerktouni, Gauthier',
          city: 'Casablanca',
          preferredDate: DateTime.now().add(const Duration(days: 3)),
          preferredTime: '08:00',
          budget: 300,
          status: RequestStatus.pending,
          paymentMethod: PaymentMethod.cash,
          createdAt: DateTime.now().subtract(const Duration(hours: 1)),
        ),
        ServiceRequest(
          id: 'req_003',
          customerId: 'user_001',
          professionalId: 'pro_003',
          customerName: 'Aziz Bennani',
          professionalName: 'Mohamed Tazi',
          category: ServiceCategory.electrician,
          description:
              'Plusieurs prises électriques ne fonctionnent plus dans le salon. Le disjoncteur saute régulièrement.',
          latitude: 33.5731,
          longitude: -7.5898,
          address: '78 Rue Ibn Batouta, Ain Sebaa',
          city: 'Casablanca',
          preferredDate: DateTime.now().subtract(const Duration(days: 2)),
          preferredTime: '14:00',
          budget: 200,
          finalPrice: 180,
          status: RequestStatus.completed,
          paymentMethod: PaymentMethod.cash,
          paymentStatus: PaymentStatus.paid,
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
          acceptedAt: DateTime.now().subtract(const Duration(days: 4)),
          completedAt: DateTime.now().subtract(const Duration(days: 2)),
        ),
      ];

  // Demo reviews
  List<ReviewModel> get reviews => [
        ReviewModel(
          id: 'rev_001',
          requestId: 'req_003',
          customerId: 'user_001',
          professionalId: 'pro_003',
          customerName: 'Aziz Bennani',
          rating: 5.0,
          comment:
              'Excellent travail! Mohamed a résolu le problème rapidement et proprement. Prix raisonnable. Je recommande vivement.',
          category: ServiceCategory.electrician,
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
        ),
        ReviewModel(
          id: 'rev_002',
          requestId: 'req_old_001',
          customerId: 'user_002',
          professionalId: 'pro_001',
          customerName: 'Karim Fassi',
          rating: 4.5,
          comment:
              'Très bon plombier. Yassine est arrivé à l\'heure et a réparé la fuite rapidement. Un peu cher mais bon travail.',
          category: ServiceCategory.plumber,
          createdAt: DateTime.now().subtract(const Duration(days: 10)),
        ),
        ReviewModel(
          id: 'rev_003',
          requestId: 'req_old_002',
          customerId: 'user_003',
          professionalId: 'pro_002',
          customerName: 'Salma El Idrissi',
          rating: 5.0,
          comment:
              'L\'appartement était impeccable après le passage de Fatima Zahra et son équipe. Service de qualité, je ferai appel à eux régulièrement.',
          category: ServiceCategory.cleaning,
          createdAt: DateTime.now().subtract(const Duration(days: 7)),
        ),
      ];

  // Demo notifications
  List<NotificationModel> get notifications => [
        NotificationModel(
          id: 'notif_001',
          userId: 'user_001',
          type: NotificationType.requestAccepted,
          title: 'Demande acceptée',
          body: 'Yassine El Amrani a accepté votre demande de plomberie.',
          data: {'request_id': 'req_001'},
          createdAt: DateTime.now().subtract(const Duration(hours: 1)),
        ),
        NotificationModel(
          id: 'notif_002',
          userId: 'user_001',
          type: NotificationType.newMessage,
          title: 'Nouveau message',
          body: 'Mohamed Tazi vous a envoyé un message.',
          data: {'conversation_id': 'conv_001'},
          createdAt: DateTime.now().subtract(const Duration(hours: 2)),
        ),
        NotificationModel(
          id: 'notif_003',
          userId: 'user_001',
          type: NotificationType.serviceCompleted,
          title: 'Service terminé',
          body:
              'Votre service d\'électricité a été marqué comme terminé. N\'oubliez pas de laisser un avis!',
          data: {'request_id': 'req_003'},
          isRead: true,
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
        ),
        NotificationModel(
          id: 'notif_004',
          userId: 'user_001',
          type: NotificationType.system,
          title: 'Bienvenue sur Khddam.ma!',
          body:
              'Découvrez des professionnels de confiance près de chez vous. Commencez par rechercher un service.',
          isRead: true,
          createdAt: DateTime.now().subtract(const Duration(days: 30)),
        ),
      ];

  // Demo conversations
  List<ChatConversation> get conversations => [
        ChatConversation(
          id: 'conv_001',
          requestId: 'req_001',
          otherUserId: 'user_pro_001',
          otherUserName: 'Yassine El Amrani',
          lastMessage: 'D\'accord, je serai là demain à 10h incha\'Allah.',
          lastMessageAt: DateTime.now().subtract(const Duration(hours: 1)),
          unreadCount: 1,
          isOnline: true,
        ),
        ChatConversation(
          id: 'conv_002',
          requestId: 'req_003',
          otherUserId: 'user_pro_003',
          otherUserName: 'Mohamed Tazi',
          lastMessage: 'Merci pour votre avis! À bientôt.',
          lastMessageAt: DateTime.now().subtract(const Duration(days: 2)),
          unreadCount: 0,
          isOnline: false,
        ),
      ];

  // Demo chat messages
  List<ChatMessage> getMessages(String conversationId) {
    if (conversationId == 'conv_001') {
      return [
        ChatMessage(
          id: 'msg_001',
          senderId: 'user_001',
          receiverId: 'user_pro_001',
          requestId: 'req_001',
          content:
              'Bonjour, j\'ai une fuite d\'eau dans la cuisine. Vous êtes disponible demain matin?',
          createdAt: DateTime.now().subtract(const Duration(hours: 3)),
          isRead: true,
        ),
        ChatMessage(
          id: 'msg_002',
          senderId: 'user_pro_001',
          receiverId: 'user_001',
          requestId: 'req_001',
          content:
              'Bonjour! Oui, je suis disponible demain matin. C\'est quel type de fuite? Sous l\'évier ou au niveau du robinet?',
          createdAt: DateTime.now().subtract(const Duration(hours: 2, minutes: 45)),
          isRead: true,
        ),
        ChatMessage(
          id: 'msg_003',
          senderId: 'user_001',
          receiverId: 'user_pro_001',
          requestId: 'req_001',
          content:
              'Sous l\'évier, au niveau du siphon je pense. L\'eau coule doucement.',
          createdAt: DateTime.now().subtract(const Duration(hours: 2, minutes: 30)),
          isRead: true,
        ),
        ChatMessage(
          id: 'msg_004',
          senderId: 'user_pro_001',
          receiverId: 'user_001',
          requestId: 'req_001',
          content:
              'D\'accord, je serai là demain à 10h incha\'Allah. Le prix sera entre 100 et 150 DH selon la pièce à changer.',
          createdAt: DateTime.now().subtract(const Duration(hours: 1)),
          isRead: false,
        ),
      ];
    }
    return [];
  }

  // Professional dashboard stats
  Map<String, dynamic> get professionalStats => {
        'today_requests': 3,
        'pending_requests': 12,
        'completed_jobs': 48,
        'earnings_today': 450,
        'earnings_week': 2350,
        'earnings_month': 4850,
        'earnings_total': 38500,
        'rating': 4.8,
        'review_count': 124,
      };

  // Professional earnings transactions
  List<Map<String, dynamic>> get transactions => [
        {
          'id': 'txn_001',
          'service': 'Plomberie - Réparation fuite',
          'customer': 'Karim Fassi',
          'amount': 150,
          'date': DateTime.now().subtract(const Duration(hours: 5)),
          'status': 'paid',
        },
        {
          'id': 'txn_002',
          'service': 'Plomberie - Installation robinet',
          'customer': 'Salma El Idrissi',
          'amount': 250,
          'date': DateTime.now().subtract(const Duration(days: 1)),
          'status': 'paid',
        },
        {
          'id': 'txn_003',
          'service': 'Plomberie - Débouchage',
          'customer': 'Ahmed Berrada',
          'amount': 100,
          'date': DateTime.now().subtract(const Duration(days: 2)),
          'status': 'paid',
        },
        {
          'id': 'txn_004',
          'service': 'Plomberie - Réparation chauffe-eau',
          'customer': 'Nadia Chakir',
          'amount': 350,
          'date': DateTime.now().subtract(const Duration(days: 3)),
          'status': 'paid',
        },
        {
          'id': 'txn_005',
          'service': 'Plomberie - Installation sanitaire',
          'customer': 'Omar Zniber',
          'amount': 800,
          'date': DateTime.now().subtract(const Duration(days: 5)),
          'status': 'paid',
        },
      ];
}
